// Generated by CoffeeScript 1.6.2
(function() {
  define(function() {
    return {
      setup: function(local, done) {
        return require(["ural/localization/" + local + "/controller.text"], function(controllerText) {
          window.localization = {
            controller: {
              text: controllerText
            }
          };
          if (done) {
            return done();
          }
        });
      }
    };
  });

}).call(this);
