// Generated by CoffeeScript 1.6.2
(function() {
  define(["ural/bindings/autocomplete", "ural/bindings/tag-edit", "ural/bindings/date", "ural/bindings/knockout.bindings", "ural/bindings/link", "ural/bindings/tooltip", "ural/bindings/drag-and-drop"], function(autocomplete, tagedit) {
    return {
      autocomplete: autocomplete,
      tagedit: tagedit
    };
  });

}).call(this);

/*
//@ sourceMappingURL=_all.map
*/
