// Generated by CoffeeScript 1.6.2
(function() {
  define(function() {
    return ko.bindingHandlers.tooltip = {
      init: function(element, valueAccessor) {
        $(element).tooltip({
          title: function() {
            var val;

            val = ko.utils.unwrapObservable(valueAccessor());
            if ($.isArray) {
              return val.join('\n');
            } else {
              return val;
            }
          }
        });
        return ko.utils.domNodeDisposal.addDisposeCallback(element, function() {
          $(element).tooltip("hide");
          return $(element).triggerHandler("destroyed");
        });
      }
    };
  });

}).call(this);
